---
abstract: 'Parse FOAF (Friend of a Friend) data'
author:
  - Benjamin
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-FOAF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  RDF::Core: 0
  URI: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/btrott/XML-FOAF.git
version: 0.04
